# Generated by Django 5.2.3 on 2025-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('hiring', 'Hiring Challenge'), ('quiz', 'Quiz/Trivia'), ('hackathon', 'Hackathon'), ('internship', 'Internship'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
